#---------------------------------------------------------------------------
#	decision.py
#
#	Description:
#
#	An object that contains a player decision generated by an AI or an
#	interface. All players must pass a decision on each play, however all
#	non-active players can only pass the decision "Wait"
#---------------------------------------------------------------------------

#---------------------------------------------------------------------------
#	Decision class
#---------------------------------------------------------------------------

class Decision():
	
	WAIT = "WAIT"
	FOLD = "FOLD"
	CHECK = "CHECK"
	REVEAL = "REVEAL"
	CALL = "CALL"
	RAISE = "RAISE"
	FORFEIT = "FORFEIT"
	GAMEQUIT = "GAMEQUIT"
	
	#---------------------------------------------------------------------------
	#	Constructor
	#
	#	Passed a decision name and a value
	#---------------------------------------------------------------------------
	def __init__(self, name = "WAIT", value = 0):
		
		name = name.upper()
		
		assert (name == self.WAIT or 
				name == self.FOLD or
				name == self.CHECK or
				name == self.REVEAL or
				name == self.CALL or
				name == self.RAISE or
				name == self.FORFEIT or
				name == self.GAMEQUIT)
		
		self.name = name.upper()
		self.value = value
		
	 